# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define :maestro do |maestro|
      maestro.vm.box = "bento/ubuntu-22.04"
      maestro.vm.network :private_network, ip: "192.168.50.3"
      maestro.vm.hostname = "maestro"
      # Configuración del proveedor (VirtualBox)
      maestro.vm.provider "virtualbox" do |vb|
        vb.memory = "1000"  # 500 MB de RAM
        vb.cpus = 1        # 1 núcleo de CPU
      end
    end
  
    config.vm.define :secundario do |secundario|
      secundario.vm.box = "bento/ubuntu-22.04"
      secundario.vm.network :private_network, ip: "192.168.50.2"
      secundario.vm.hostname = "secundario"
      # Configuración del proveedor (VirtualBox)
      secundario.vm.provider "virtualbox" do |vb|
        vb.memory = "1000"  # 500 MB de RAM
        vb.cpus = 1        # 1 núcleo de CPU
      end
    end

    config.vm.define :firewall do |firewall|
      firewall.vm.box = "bento/ubuntu-22.04"
      firewall.vm.network :private_network, ip: "192.168.50.4"
      firewall.vm.hostname = "firewall"
      # Configuración del proveedor (VirtualBox)
      firewall.vm.provider "virtualbox" do |vb|
        vb.memory = "1000"  # 500 MB de RAM
        vb.cpus = 1        # 1 núcleo de CPU
      end
    end
end